### PR TITLE
Add dashboard

### PR DESCRIPTION
**Pull request by Abiral-2724**
Added a responsive dashboard page in the web collection .

### CODE REVIEW

**Comment by sestopus** [comment]
Also add your project name and small description in the same format as other files in the array ProjectFiles. See from line no 115(may be changed look for projectFiles) in index.html file.

**Comment by Abiral-2724** [comment]
sorry for the inconvience .

**Comment by Abiral-2724** [comment]
added to required detail , and raised a new pull request

**Comment by Abiral-2724** [comment]
pull request merged but no name in contributor

**Pull request merged**
